### PR TITLE
Suffix option

### PR DESCRIPTION
**Pull request by sp00m**
Added a `suffix` option that helps handling cache busting.

### CODE REVIEW

**Comment by soncodi** [comment]
Thanks!

**Comment by sp00m** [comment]
That was quick, thanks! Could you also `git tag` and `npm publish` when you have few minutes so that I can start using the `suffix` option? Thanks :)

**Comment by soncodi** [comment]
@sp00m just published

**Comment by sp00m** [comment]
Awesome, thanks ;)

**Pull request merged**
